level_1 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS  W  EW           W     W",
    "WWW W WWW WWWWWWW W W WWW W",
    "W W W W   W*W     W W W   W",
    "W W W W WWW W WWWWW W W WWW",
    "W   W W   W W   W W W W   W",
    "W WWW WWW W WWW W W W WWW W",
    "W W   W     W   W W W   W W",
    "W W WWW WWWWW WWW W WWW W W",
    "W W W   W     W     W   W W",
    "W W W WWW WWWWW WWWWW WWW W",
    "W W     W W*      W W   W W",
    "W W WWWWW WWWWWWW W WWW W W",
    "W W W   W       W     W W W",
    "W WWW W WWWWW W WWW WWW W W",
    "W     W     W W   W*W   W W",
    "WWWWWWWWWWW W WWW WWW WWW W",
    "W*W     W   W  *W       W W",
    "W W W WWW WWWWWWWWWWWWWWW W",
    "W   W                     W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level_2 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW               W       W",
    "W WWW WWW WWWWW WWW WWWWW W",
    "W   W W   W   WEW   W   W W",
    "WWW WWW W W W WWW WWW WWW W",
    "W*W   W W W W         W   W",
    "W WWW W WWW WWWWWWWWW W WWW",
    "W W   W     W     W   W   W",
    "W W WWWWWWW W WWW WWW WWW W",
    "W W W     W W W W   W  *W W",
    "W W W WWW WWW W WWW WWWWW W",
    "W W   W W     W  *W     W W",
    "W WWWWW WWWWWWW WWWWWWW W W",
    "W W     W           W   W W",
    "W W W WWW WWWWWWWWW W WWW W",
    "W   W     W*      W   W   W",
    "W WWWWWWWWWWWWWWW WWWWW W W",
    "W W     W       W       W W",
    "W WWW W WWW WWW W WWWWWWW W",
    "W     W     W     W*      W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW"
]

level_3 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW       W  *W       W   W",
    "W W WWWWW W WWW WWW W W W W",
    "W W W   W W     W   W W*W W",
    "W W W W W WWWWWWW WWW WWW W",
    "W   W W   W       W W W   W", 
    "WWWWW WWWWW WWWWWWW W W WWW",
    "W     W     W*    W   W   W",
    "W WWWWWWWWW WWWWW W WWWWW W",
    "W W       W   W   W W     W",
    "W W WWWWW WWW W WWW W W W W",
    "W W W   W     W W   W W W W",
    "W W W W WWWWWWW W WWW W W W",
    "W W W W     W W   W*  W W W",
    "W W W WWW W W W WWWWWWW WWW",
    "W   W   W W   W       W   W",
    "WWWWW WWW WWW WWWWWWW W W W",
    "W     W   W    *W   W W W W",
    "W WWWWW WWWWWWWWW W W WWW W",
    "W    EW           W       W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWW" 
]

level_4 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW*              W         W",
    "W WWWWWWWWW WWWWW W WWWWWWW W",
    "W       W   W     W     W*W W",
    "WWWWWWW W WWW WWWWW WWW W W W",
    "W    *W W W   W   W   W W   W",
    "W WWWWW W W WWW W WWW W WWWWW",
    "W W   W   W W   W   W W W   W",
    "W W W WWWWW WWW WWW W W W W W",
    "W   W     W   W   W   W   W W",
    "W WWWWWWW WWW WWW WWWWWWWWW W",
    "W      *W   W W   WE      W W",
    "W WWWWWWWWW W W WWWWWWWWW W W",
    "W W       W W W           W W",
    "W W WWWWW W W WWWWWWWWWWW W W",
    "W W   W*W   W W     W   W W W",
    "WWWWW W W WWW W WWW W W WWW W",
    "W     W   W   W W     W   W W",
    "W WWWWWWWWW WWW WWWWWWWWW W W",
    "W     W   W   W   W*W     W W",
    "W WWW W W WWW WWW W W WWWWW W",
    "W   W   W         W         W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_5 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS    W*    W     W       W*W",
    "WWWWW WWWWW W W WWW W WWW W W",
    "W   W     W   W W   W W W W W",
    "W W WWWWW WWWWW W WWW W W W W",
    "W W     W     W   W   W W W W",
    "W WWWWW WWWWW WWWWW WWW W W W",
    "W     W     W       W   W W W",
    "WWWWW W WWW WWWWWWWWW W W W W",
    "W   W W   W        *W W W   W",
    "W W W WWW WWWWWWWWWWW W WWW W",
    "W W   W W     W       W   W W",
    "W WWWWW WWWWW W WWWWWWW W W W",
    "W   W     W   W W*    W W W W",
    "WWW W W W W WWW WWWWW W WWW W",
    "W W W W W W W   W   W W     W",
    "W W W W WWW W WWW W W WWWWWWW",
    "W W W W W   W W   W W   W*  W",
    "W W W W W WWW WWW W W W WWW W",
    "W   WEW W   W W   W   W   W W",
    "W WWWWW WWW W W WWWWWWWWW W W",
    "W         W     W*          W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_6 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW             W  EW   W   W",
    "W WWWWWWWWW WWW W WWW W W W W",
    "W W         W   W     W   W W",
    "W W WWWWWWWWW WWWWWWWWWWWWW W",
    "W W   W     W   W       W   W",
    "W W W W WWW WWW W WWWWW W W W",
    "W W W   W   W W   W   W W W W",
    "W W WWWWW WWW WWWWW WWW W W W",
    "W W    *W W     W W     W W W",
    "W WWWWWWW W W W W W WWWWW WWW",
    "W W       W W W   W W W     W",
    "W W WWWWWWW W W WWW W W WWW W",
    "W W     W*  W W W   W   W*W W",
    "W W WWW WWWWW W W WWW WWW W W",
    "W W   W   W   W*W   W     W W",
    "W WWWWWWW W WWWWWWW WWWWWWW W",
    "W       W W         W       W",
    "WWWWWWW W W WWWWWWWWW WWWWW W",
    "W    *W   W   W       W*W   W",
    "W WWWWWWWWWWW WWW WWWWW W WWW",
    "W                 W         W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_7 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW       W     W         W*W",
    "W W W WWW WWW WWW WWWWW W W W",
    "W W W W W   W   W W*W   W W W",
    "W WWW W WWW W W W W W WWW W W",
    "W     W   W W W   W W W     W",
    "WWWWWWW WWW W WWWWW W WWWWWWW",
    "W*  W       W W     W       W",
    "WWW W WWWWWWW W W WWWWWWWWW W",
    "W   W   W     W W W         W",
    "W WWWWW WWW WWW WWW WWWWWWW W",
    "W W   W   W     W   W   W   W",
    "W W W WWW WWWWW W WWW W W WWW",
    "W W W W   W*W   W   W*W     W",
    "W W W W WWW W WWWWW WWWWWWWWW",
    "W   W W   W W W   W   W     W",
    "W WWW WWW W W W W WWW W WWW W",
    "W   W   W W     W   W   W   W",
    "W WWW WWW W WWWWWWW WWWWW W W",
    "W W   W   W W     W WEW   W W",
    "W W W W WWWWW WWW W W W WWW W",
    "W W W W   W   W   W   W W   W",
    "W W WWWWW W WWW WWWWWWW W WWW",
    "W*W         W           W  *W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_8 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW*W         W   W     W   W",
    "W W W WWW WWW W W W W W W W W",
    "W W     W W     W*W W W   W W",
    "W WWWWWWW WWW WWWWW W WWWWW W",
    "W       W   W W     W     W*W",
    "WWWWWWW W W WWW WWWWWWWWW WWW",
    "W       W W   W     W  EW   W",
    "W WWWWWWWWW W WWWWW W WWWWW W",
    "W W       W W       W     W W",
    "W WWWWW W WWWWW WWWWWWWWW W W",
    "W       W     W   W     W W W",
    "WWWWWWWWWWWWW WWW W WWW W W W",
    "W       W*W   W W W W W W W W",
    "WWW WWW W W WWW W W W W W W W",
    "W   W     W W   W   W   W W W",
    "W WWW WWWWW W WWWWWWW WWW W W",
    "W   W   W   W       W W   W W",
    "W W WWW W WWWWW WWW W WWW W W",
    "W W W   W     W   W       W W",
    "W W W WWWWWWW WWW WWWWWWWWW W",
    "W W W W     W W    *W       W",
    "W W WWW WWW W WWWWWWW WWWWW W",
    "W*W      *W           W     W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_9 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS  W       W*              W",
    "WWW WWWWW W WWWWWWWWW WWWWW W",
    "W W   W   W     W   W    *W W",
    "W WWW W WWWWWWW W W WWWWWWW W",
    "W W   W W     W W W W   W   W",
    "W W WWW WWW W W W W W W W W W",
    "W   W   W   W W   W   W   W W",
    "W WWWWW W WWW WWWWWWWWWWWWW W",
    "W W     W W     W       W   W",
    "W W WWWWW W WWWWW WWWWW W WWW",
    "W   W     W*W     W W   W   W",
    "WWWWWWW WWWWW WWWWW W WWWWW W",
    "W*      W     W*    W W     W",
    "WWWWW W W WWWWWWWWW W W WWWWW",
    "W     W W       W   W   W   W",
    "W WWW WWWWWWWWW W WWWWWWW W W",
    "W   W W         W       WEW W",
    "WWW W W WWWWWWWWWWWWW W WWW W",
    "W   W W W*          W W   W W",
    "W WWWWW WWWWWWW WWW W WWW W W",
    "W W   W   W   W W*W   W   W W",
    "W W W WWW W W W W WWWWW WWW W",
    "W   W       W   W           W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_10 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS    W     W                 W",
    "WWWWW WWW W W WWW WWWWWWWWWWW W",
    "W   W   W W W W W W         W W",
    "W W WWW WWW W W W W WWWWWWWWW W",
    "W W   W   W W   W W   W     W W",
    "WWW W WWW W W WWW WWW W WWW W W",
    "W   W W   W   W   W   W   W   W",
    "W WWWWW WWW WWW WWW W WWW WWWWW",
    "W W     W   W   W   W   W W   W",
    "W W WWWWWWWWW WWW WWWWW W WWW W",
    "W   W       W W     W W W     W",
    "W WWW W WWW W W WWW W W WWWWW W",
    "W W   W   W   W   W W       W W",
    "W WWWWWWW WWWWWWWWW WWWWWWW W W",
    "W         W         W   WE  W W",
    "WWWWWWWWWWW WWWWW WWW W WWWWW W",
    "W W         W   W W   W   W   W",
    "W W WWW WWWWW W W W WWWWW W WWW",
    "W W W W   W   W   W   W W   W W",
    "W W W WWW WWWWWWWWWWW W WWWWW W",
    "W W   W   W   W     W   W     W",
    "W WWW W WWW W W W WWWWW W WWW W",
    "W     W     W   W         W   W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_11 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS          W W               W",
    "WWWWWWWWWWW W W W WWWWWWW WWWWW",
    "W   W   W   W   W   W     W   W",
    "W W W WWW WWW WWWWW W WWWWW W W",
    "W W W   W   W W     W   W   W W",
    "W W WWW WWW W W W WWWWW W WWW W",
    "W W W   W   W W W W   WEW   W W",
    "W W W WWW WWWWW WWW W WWWWW W W",
    "W W   W   W   W W   W     W W W",
    "W WWWWW WWW W W W WWWWWWW W W W",
    "W W   W     W W   W     W   W W",
    "W W W WWWWWWW WWWWW WWW W WWW W",
    "W   W     W W W     W W W   W W",
    "W WWWWW W W W W WWWWW W WWWWW W",
    "W W   W W   W W     W W       W",
    "W W W W WWWWW W WWW W WWWWWWW W",
    "W W W W W     W W   W W   W   W",
    "W W W W W WWWWWWW WWW W W W WWW",
    "W   W W   W       W W   W   W W",
    "WWWWW WWWWWWW WWWWW W WWWWWWW W",
    "W W   W     W W     W       W W",
    "W W WWW WWW W W W WWWWWWWWW W W",
    "W       W     W W             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_12 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WS  W   W           W         W",
    "WWW W WWW WWWWW WWW WWWWW WWW W",
    "W W W   W   W   W   W   W   W W",
    "W W WWW WWW W WWWWW W W WWW WWW",
    "W W   W     W     W W W   W   W",
    "W WWW W WWWWWWWWW W W WWW W W W",
    "W   W W W   W     W W   W W W W",
    "W WWW W WWW W WWWWW WWW W WWW W",
    "W   W W     W   W       W W   W",
    "W W W WWWWW WWW WWWWWWWWW W W W",
    "W W W     W   W       W   W W W",
    "W W WWWWW WWWWWWW WWW WWW W W W",
    "W W W     W     W   W   W   W W",
    "W W W WWWWW WWW WWW WWW WWWWW W",
    "WEW W   W   W W   W   W W   W W",
    "WWW WWW W WWW WWW WWWWW W W W W",
    "W   W   W   W   W       W W   W",
    "W WWW WWWWW W WWWWWWWWWWW WWWWW",
    "W   W       W   W     W   W   W",
    "W W WWWWWWWWWWW W W WWW WWWWW W",
    "W W     W       W W     W     W",
    "W WWWWW W WWW WWW WWWWWWW WWW W",
    "W     W     W             W   W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_13 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW W             W     W   W     W",
    "W W W WWWWW WWWWW W WWW W W WWW W W",
    "W W W W W   W   W W   W   W   W W W",
    "W W W W W WWW W W WWW WWWWWWW WWW W",
    "W W W   W W   W W   W W   W W   W W",
    "W W W WWW W WWW WWW W W W W WWW W W",
    "W W   W   W W   W   W   W W   W   W",
    "W WWWWW WWW W WWW WWWWWWW WWW WWW W",
    "W       W   W W   W       W   W W W",
    "WWWWWWWWW WWW W WWW WWWWWWW W W W W",
    "W   W   W W W   W   W       W W W W",
    "W W WWW W W WWWWW WWW WWWWW W W W W",
    "W W     W     W   W   W     W W W W",
    "W WWWWW WWWWW WWW WWWWW WWWWW W W W",
    "W W         W     W     W   W   W W",
    "W W WWWWWWWWWWWWWWW W WWW W WWWWW W",
    "W W W     W     W   W W   W       W",
    "W W W WWW W W WWW W WWW WWWWWWWWWWW",
    "W W W   W W W     W   W W         W",
    "W WWW WWW W WWWWWWWWW W WWWWW WWW W",
    "W W   W   W W       W   W     W   W",
    "W W WWW WWW WWWWWWW WWWWW WWWWW WWW",
    "W W W W W   W     W   W   W   W   W",
    "W W W W W WWW WWW W W W W W W WWW W",
    "W   W W W W     W W W W W WEW W   W",
    "W WWW W W WWWWW W WWW W W WWW W WWW",
    "W W   W W   W   W   W   W   W W W W",
    "W W W W WWW W WWWWW WWWWWWW W W W W",
    "W   W W       W             W     W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_14 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW   W           W     W       W W",
    "W W WWW WWWWW WWW W W W WWWWW W W W",
    "W W       W   W   W W W       W   W",
    "W WWWWWWWWW WWW WWW W WWWWWWWWWWW W",
    "W         W   W W   W W       W   W",
    "WWWWWWWWW WWW WWW WWW W WWWWW W WWW",
    "W       W   W       W W   W W W W W",
    "W WWWWWWWWW WWWWWWW W WWW W W W W W",
    "W   W       W   W   W   W W   W   W",
    "WWW W WWWWWWW W WWWWWWW W W WWWWW W",
    "W   W     W   W W       W W     W W",
    "W WWWWWWW WWW W W WWWWWWW WWWWWWW W",
    "W       W     W W     W W         W",
    "W WWW W WWWWWWW W WWW W W WWWWWWWWW",
    "W W W W   W   W W W   W W W       W",
    "W W W WWW W W W WWW WWW W W WWWWW W",
    "W W W   W W W W W   W   W W W   W W",
    "W W WWW WWW W W W WWW W W W W W W W",
    "W     W W   W W W W   W W W   W WEW",
    "WWWWW W W WWW W W W W WWW WWWWW WWW",
    "W   W W W W W   W W W     W   W   W",
    "W WWW W W W WWWWW W WWWWWWW W WWW W",
    "W     W W W     W W W       W   W W",
    "WWWWWWW W WWW W W W WWW WWWWWWW W W",
    "W     W W W   W W W     W W     W W",
    "W WWW W W W WWW W WWWWWWW W WWWWW W",
    "W W     W W W   W   W     W     W W",
    "W WWWWWWW W W WWWWW W WWW WWWWW W W",
    "W           W       W   W         W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
level_15 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WSW   W           W   W         W W",
    "W W W WWWWWWW W W W W W W WWWWW W W",
    "W W W       W W W W W W W W   W W W",
    "W W WWWWWWW WWW W W W W W W WWW W W",
    "W   W     W     W W W   W W   W   W",
    "WWWWW WWWWWWWWWWW WWW WWW W W WWW W",
    "W       W       W   W W   W W   W W",
    "W WWWWW W W WWWWWWW W W WWWWW W W W",
    "W     W W W   W     W W     W W   W",
    "WWWWWWW W WWW W WWWWWWWWWWW WWWWW W",
    "W       W W W W W     W   W     W W",
    "W WWWWW W W W W WWW W W W W WWW WWW",
    "W   W W W W W W     W W W W W W   W",
    "WWW W W W W W WWWWWWW W W W W WWW W",
    "W   W   W W W       W   W W   W   W",
    "W WWWWWWW W WWWWW WWWWWWW W WWW W W",
    "W W       W     W     W   W W   W W",
    "W W WWWWWWWWW W WWWWW W WWWWW WWW W",
    "W   W         W    EW W     W W   W",
    "W WWWWW WWWWWWWWWWWWW WWWWW W W WWW",
    "W     W             W     W   W   W",
    "WWWWW WWWWW WWWWWWW WWW WWWWWWWWW W",
    "W   W     W W     W   W     W W   W",
    "W W WWWWW W W WWW W W WWW W W W WWW",
    "W W   W   W W W   W W   W W   W W W",
    "W W WWW WWW W W WWW WWW W WWWWW W W",
    "W W     W   W W   W W W W       W W",
    "W WWWWWWWWWWW WWW W W W WWWWWWWWW W",
    "W             W     W             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]
all_levels = [level_1, level_2, level_3, level_4, level_5, level_6, level_7, level_8, level_9, level_10, level_11, level_12, level_13, level_14, level_15]